name: "Check PR Description on Comment"

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'trigger action')
    name: Analyze
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch
        env:
          PULL_REQUEST_URL: ${{ github.event.issue.pull_request.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set_branch
        run: |
          mkdir -p .ci-temp
          curl --fail-with-body -X GET "${PULL_REQUEST_URL}" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -o .ci-temp/info.json

          jq --raw-output .head.ref .ci-temp/info.json > .ci-temp/branch
          jq --raw-output .head.sha .ci-temp/info.json > .ci-temp/commit_sha

          BRANCH_NAME=$(cat .ci-temp/branch)
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          
      - name: Display fetched branch and commit information
        run: |
          echo "Branch: $(cat .ci-temp/branch)"
          echo "Commit SHA (short): $(cat .ci-temp/commit_sha | cut -c 1-7)"

      - name: Verify branch name
        run: |
          echo "Branch to checkout: ${{ env.BRANCH_NAME }}"
          
      - name: Checkout the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }} # Checkout the PR branch using the env variable

      - name: Display current branch
        run: |
          echo "You are now on branch: $(git rev-parse --abbrev-ref HEAD)"
          
      - name: Do action based on comment
        env:
          READ_ONLY_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PULL_REQUEST: '${{ github.event.issue.number }}'
        run: |
          echo "Triggering action based on PR comment"
          ./.ci/pr-description.sh
